version: '3.8'

services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=puj_mflow_models
      - GRANT_SUDO=yes
    
    command: start-notebook.sh --NotebookApp.token=''

    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: puj_mflow_models
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: